export const CREATE_TRIP_REQUEST = "CREATE_TRIP_REQUEST";
export const CREATE_TRIP_SUCCESS = "CREATE_TRIP_SUCCESS";
export const CREATE_TRIP_FAILURE = "CREATE_TRIP_FAILURE";

export const ALL_TRIPS_REQUEST = "ALL_TRIPS_REQUEST";
export const ALL_TRIPS_SUCCESS = "ALL_TRIPS_SUCCESS";
export const ALL_TRIPS_FAILURE = "ALL_TRIPS_FAILURE";

export const DELETE_TRIPS_REQUEST = "DELETE_TRIPS_REQUEST";
export const DELETE_TRIPS_SUCCESS = "DELETE_TRIPS_SUCCESS";
export const DELETE_TRIPS_FAILURE = "DELETE_TRIPS_FAILURE";

export const TRIP_DETAIL_REQUEST = "TRIP_DETAIL_REQUEST";
export const TRIP_DETAIL_SUCCESS = "TRIP_DETAIL_SUCCESS";
export const TRIP_DETAIL_FAILURE = "TRIP_DETAIL_FAILURE";

export const ADD_TRIP = "ADD_TRIP";
export const REMOVE_TRIP = "REMOVE_TRIP";
export const SET_CURRENT_TRIP = "SET_CURRENT_TRIP";

export const CLEAR_ERROR = "CLEAR_ERROR";
